#C:\Users\panga\Downloads\Selenium Framework1\Selenium Framework1\Reports\Report10-16-2022\10-16-2022_213543PM\DataCompare_10-16-2022_213543PM.xlsm
#Sun Oct 16 21:35:44 IST 2022
renewalPolicyNumberUAT=
regressionScenario=
renewalPolicyNumberQA=
compareRegressionData=C\:\\Users\\panga\\Downloads\\Selenium Framework1\\Selenium Framework1\\Reports\\Report10-16-2022\\10-16-2022_213543PM\\DataCompare_10-16-2022_213543PM.xlsm
orFilePath=.\\DataRepository\\OR_ESurety.xlsx
formsComparisonResult=\\Reports\\Report04-29-2022\\04-29-2022_203454PM\\FormCompare-04-29-2022_203454PM.xlsx
2022_20-27-18=PM.xlsx
testDataScenario=
bondNumber=TCS11819
emailIDPath=
insuredName=
rackingID=12142113423049063212
12142113423049063212=
renewalPolicySuffixUAT=01
reportPath=\\Reports\\Report
projectPath=C\:\\Users\\panga\\Downloads\\Selenium Framework1\\Selenium Framework1
RenewalformsComparisonResult=\\Reports\\Report04-29-2022\\04-29-2022_203454PM\\RenewalFormCompare-04-29-2022_203454PM.xlsx
RenewalformsComparisonTemplate=G\:\\Hudson Systems\\QA TCoE\\QA Test Artifacts 2022\\Selenium Automation\\ESurety\\ESurety\\Reports\\Report04-29-2022\\04-29-2022_203454PM\\RenewalFormCompare-04-29-2022_203454PM.xlsx
PM.xlsx=
capturedValue=32399
envCompare=\\Reports\\Template for Env Data Comparison.xlsm
EmailResultPath=\\Reports\\Report10-16-2022\\10-16-2022_213543PM\\Report_Summary_10-16-2022_213543PM.html
actualOutputBond=G\:\\Hudson Systems\\QA TCoE\\QA Test Artifacts 2021\\HSF Automation\\ESurety\\ESurety\\Reports\\Report12-14-2021\\12-14-2021_190914PM\\NewBond_Agent Portal_  Lost Security - Open Penalty_AZ_UAT.pdf
subFolderName=\\Reports\\Report10-16-2022\\10-16-2022_213543PM
renewalPolicySuffixQA=
8=PM.xlsx
formsComparisonTemplate=G\:\\Hudson Systems\\QA TCoE\\QA Test Artifacts 2022\\Selenium Automation\\ESurety\\ESurety\\Reports\\Report04-29-2022\\04-29-2022_203454PM\\FormCompare-04-29-2022_203454PM.xlsx
2113423049063212=
trackingID=12142113423049063212
